"use client";

import {
  Badge,
  Button,
  Card,
  CardFooter,
  CardHeader,
  Text,
  makeStyles,
  tokens as fluentTokens,
} from "@fluentui/react-components";
import { Sparkle24Regular } from "@fluentui/react-icons";

type SafeTokens = { [key: string]: any };
const tokens: SafeTokens = fluentTokens;

export interface DemoTaskPrototypeProps {
  /** Display title for the generated task prototype. */
  title?: string;
  /** Short summary of what this prototype demonstrates. */
  description?: string;
}

const useStyles = makeStyles({
  root: {
    display: "grid",
    gap: tokens.spacingVerticalXL,
    minHeight: "100vh",
    alignContent: "center",
    backgroundColor: tokens.colorNeutralBackground2,
    paddingTop: tokens.spacingVerticalXXXL,
    paddingRight: tokens.spacingHorizontalXXXL,
    paddingBottom: tokens.spacingVerticalXXXL,
    paddingLeft: tokens.spacingHorizontalXXXL,
  },
  hero: {
    display: "grid",
    gap: tokens.spacingVerticalM,
    maxWidth: "760px",
  },
  eyebrow: {
    color: tokens.colorBrandForeground1,
    fontWeight: tokens.fontWeightSemibold,
  },
  title: {
    color: tokens.colorNeutralForeground1,
    fontSize: tokens.fontSizeHero800,
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeightHero800,
    marginTop: "0",
    marginRight: "0",
    marginBottom: "0",
    marginLeft: "0",
  },
  description: {
    color: tokens.colorNeutralForeground2,
    fontSize: tokens.fontSizeBase400,
    lineHeight: tokens.lineHeightBase400,
    maxWidth: "640px",
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: tokens.spacingHorizontalL,
  },
  card: {
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopColor: tokens.colorNeutralStroke2,
    borderRightColor: tokens.colorNeutralStroke2,
    borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2,
  },
});

/**
 * Starter Fluent UI v9 task prototype generated by create-task-prototype.
 * Replace the cards with the task-specific journey, states, and interactions.
 */
export default function DemoTaskPrototype({
  title = "Demo Task",
  description = "Generated demo task prototype for build verification.",
}: DemoTaskPrototypeProps) {
  const styles = useStyles();

  return (
    <main className={styles.root} aria-labelledby="demo-task-title">
      <section className={styles.hero}>
        <Badge appearance="tint" color="brand" icon={<Sparkle24Regular />}>
          Task prototype
        </Badge>
        <Text as="h1" id="demo-task-title" className={styles.title}>
          {title}
        </Text>
        <Text as="p" className={styles.description}>
          {description}
        </Text>
      </section>

      <section className={styles.cardGrid} aria-label="Prototype starter areas">
        {["Define the user moment", "Compose Fluent components", "Verify with Storybook"].map((item) => (
          <Card key={item} className={styles.card}>
            <CardHeader header={<Text weight="semibold">{item}</Text>} />
            <Text>
              Swap this starter content for task-specific screens, interaction states, and validation notes.
            </Text>
            <CardFooter>
              <Button appearance="secondary">Update section</Button>
            </CardFooter>
          </Card>
        ))}
      </section>
    </main>
  );
}
