import type { ScopeEntry } from "./engops-scope-picker"

export const MOCK_SUBSCRIPTIONS: ScopeEntry[] = [
  {
    id: "sub-1",
    name: "prod-payments",
    subtitle: "Azure subscription",
    resources: 124,
    costPerMo: "$12,480",
    tags: [
      { label: "criticality=tier-0", critical: true },
      { label: "env=prod" },
      { label: "service=payments-api" },
    ],
    defaultChecked: true,
    isCriticalProd: true,
    spendRank: 1,
  },
  {
    id: "sub-2",
    name: "prod-platform-core",
    subtitle: "Azure subscription",
    resources: 186,
    costPerMo: "$9,720",
    tags: [
      { label: "criticality=tier-0", critical: true },
      { label: "env=prod" },
    ],
    defaultChecked: true,
    isCriticalProd: true,
    spendRank: 2,
  },
  {
    id: "sub-3",
    name: "prod-edge-cdn",
    subtitle: "Azure subscription",
    resources: 58,
    costPerMo: "$3,140",
    tags: [{ label: "criticality=tier-1" }, { label: "env=prod" }],
    isCriticalProd: true,
    spendRank: 4,
  },
  {
    id: "sub-4",
    name: "prod-data-analytics",
    subtitle: "Azure subscription",
    resources: 92,
    costPerMo: "$7,190",
    tags: [{ label: "criticality=tier-1" }, { label: "env=prod" }],
    isCriticalProd: true,
    spendRank: 3,
  },
  {
    id: "sub-5",
    name: "staging-platform",
    subtitle: "Azure subscription",
    resources: 44,
    costPerMo: "$1,340",
    tags: [{ label: "env=staging" }],
    spendRank: 5,
  },
]

export const MOCK_RESOURCE_GROUPS: ScopeEntry[] = [
  {
    id: "rg-payments-api",
    name: "rg-payments-api",
    subtitle: "in prod-payments",
    resources: 47,
    costPerMo: "$4,120",
    tags: [
      { label: "criticality=tier-0", critical: true },
      { label: "env=prod" },
      { label: "service=payments-api" },
    ],
    defaultChecked: true,
    isCriticalProd: true,
    spendRank: 1,
  },
  {
    id: "rg-identity-services",
    name: "rg-identity-services",
    subtitle: "in prod-platform-core",
    resources: 38,
    costPerMo: "$3,890",
    tags: [
      { label: "criticality=tier-0", critical: true },
      { label: "env=prod" },
      { label: "service=identity" },
    ],
    defaultChecked: true,
    isCriticalProd: true,
    spendRank: 3,
  },
  {
    id: "rg-web-frontend",
    name: "rg-web-frontend",
    subtitle: "in prod-platform-core",
    resources: 62,
    costPerMo: "$2,840",
    tags: [
      { label: "criticality=tier-1" },
      { label: "env=prod" },
      { label: "service=web" },
    ],
    defaultChecked: true,
    isCriticalProd: true,
    spendRank: 4,
  },
  {
    id: "rg-analytics-core",
    name: "rg-analytics-core",
    subtitle: "in prod-data-analytics",
    resources: 41,
    costPerMo: "$4,210",
    tags: [
      { label: "criticality=tier-1" },
      { label: "env=prod" },
      { label: "team=analytics" },
    ],
    isCriticalProd: true,
    spendRank: 2,
  },
  {
    id: "rg-ml-training",
    name: "rg-ml-training",
    subtitle: "in prod-data-analytics",
    resources: 24,
    costPerMo: "$2,980",
    tags: [{ label: "env=prod" }, { label: "team=ml-platform" }],
    isCriticalProd: true,
    spendRank: 5,
  },
  {
    id: "rg-cdn-profiles",
    name: "rg-cdn-profiles",
    subtitle: "in prod-edge-cdn",
    resources: 18,
    costPerMo: "$1,420",
    tags: [{ label: "env=prod" }, { label: "service=cdn" }],
    isCriticalProd: true,
  },
  {
    id: "rg-integration-tests",
    name: "rg-integration-tests",
    subtitle: "in staging-platform",
    resources: 29,
    costPerMo: "$840",
    tags: [{ label: "env=staging" }],
  },
  {
    id: "rg-shared-logging",
    name: "rg-shared-logging",
    subtitle: "in prod-platform-core",
    resources: 15,
    costPerMo: "$610",
    tags: [{ label: "env=prod" }, { label: "service=logging" }],
    isCriticalProd: true,
  },
]
